# Generated by Django 5.0.4 on 2024-06-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem_implementasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemcerdas',
            name='nama_project',
            field=models.TextField(default='Default Project Name', max_length=255),
        ),
    ]
