# Generated by Django 5.0.4 on 2024-06-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem_implementasi', '0003_remove_sistemcerdas_nama_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pickles/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sistemcerdas',
            name='file_sistem_cerdas',
            field=models.URLField(max_length=2000),
        ),
    ]
