# Generated by Django 5.0.4 on 2024-07-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem_implementasi', '0005_csvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='project_name',
            field=models.CharField(default='Unnamed Project', max_length=255),
        ),
        migrations.AddField(
            model_name='picklefile',
            name='project_name',
            field=models.CharField(default='Unnamed Project', max_length=255),
        ),
    ]
